/**
 * AUTO-GENERATED by scripts/build-admin-guide.mjs
 * DO NOT EDIT — re-run the script or `npm run build` to regenerate.
 *
 * All admin guide articles, pre-parsed from src/content/admin-guide/
 * at build time. Zero runtime fs access required.
 */

import type { GuideArticle } from "./admin-guide";

export const GUIDE_ARTICLES: GuideArticle[] = [
  {
    slug: "content/about-page",
    title: "Updating About Us",
    category: "Content",
    tags: ["about","content","storefront"],
    order: 1,
    href: "/admin/guide/content/about-page",
    content: `# Updating About Us

The About Us page lives at \`/about\` on the storefront. It introduces your business to customers — who you are, why you started 3D Ninjaz, and what makes your products special.

## How to update it

The About page content is currently managed by editing the source code. It's not yet in the admin panel as an editable page.

To change the About page content, ask your developer to update the file at:
\`src/app/(store)/about/page.tsx\`

## What to include on your About page

A good About page for a small business covers:

- **Your story** — how you started 3D printing and why
- **What you make** — types of products, materials used
- **Quality commitment** — how you ensure products are well-finished
- **Location** — where you're based (Malaysia — which state/city)
- **Contact** — your WhatsApp number or email

## Making it personal

Customers buy from people they trust. A photo of you (or your printer in action) makes the page much more trustworthy than a stock image. Consider adding:
- A photo of your workspace
- A photo of products being packed
- A short video of a print in progress

## Social links on the About page

Social icons on the About page pull from the URLs you set in **Settings → Social & Contact**. Make sure those URLs are filled in — they appear at the bottom of the About page automatically.

**Storefront page:** \`/about\``,
  },
  {
    slug: "content/contact-page",
    title: "Contact page and social links",
    category: "Content",
    tags: ["contact","social","settings"],
    order: 2,
    href: "/admin/guide/content/contact-page",
    content: `# Contact page and social links

The Contact page lives at \`/contact\` on the storefront. It shows your contact details and social links.

## Updating contact details

Contact details are pulled from **Settings**. To update them:

1. Go to **Settings** in the sidebar.
2. In the **Social & Contact** section, update:
   - **Contact email**
   - **Contact phone** (optional)
   - **WhatsApp number** (digits only) and **display format**
3. Click **Save settings**.

Changes appear on the storefront within about 60 seconds (the data is cached for performance).

## Social links

Social icons on the Contact page (and in the storefront footer) come from the social URLs you set in Settings. Supported platforms:

- Twitter / X
- WhatsApp
- Instagram
- Facebook
- TikTok
- Review link (Google Reviews, Trustpilot, etc.)

Leave any URL blank to hide that platform's icon. You don't need to have all of them — only fill in the ones you actually use.

## WhatsApp link format

The WhatsApp number field expects **digits only** in E.164 format (no \`+\`, no spaces):
- Correct: \`60167203048\`
- Wrong: \`+60167203048\` or \`016-720 3048\`

The system builds the \`wa.me/\` deep-link automatically from this number.

**Admin page:** \`/admin/settings\`

**Storefront page:** \`/contact\``,
  },
  {
    slug: "content/maintenance",
    title: "Enabling maintenance mode",
    category: "Content",
    tags: ["maintenance","downtime","settings"],
    order: 3,
    href: "/admin/guide/content/maintenance",
    content: `# Enabling maintenance mode

Maintenance mode redirects all storefront visitors to a "We'll be right back" page while you make changes or perform maintenance. The admin panel remains accessible so you can work while the store is down.

## When to use it

- Updating a large batch of products and you don't want customers to see half-finished listings
- Server maintenance by your hosting provider
- Running a major sale setup (to avoid orders coming in before prices are ready)

## How to enable

Maintenance mode is controlled by a **server environment variable**. It cannot be toggled from the admin panel — you (or your server administrator) must change it on the server.

**To enable:**
Set \`MAINTENANCE_MODE=true\` in your server environment, then restart the Node.js app.

**To disable:**
Set \`MAINTENANCE_MODE=false\` (or remove the variable entirely), then restart the app.

## What customers see

Customers visiting any storefront page are redirected to \`/maintenance\` — a branded page with the 3D Ninjaz logo that says the store will be back shortly.

## What stays accessible during maintenance

Even when maintenance mode is on, these remain accessible:
- \`/admin/**\` — the full admin panel
- \`/payment-links/**\` — customers paying for manual orders can still complete payment
- \`/api/paypal/webhook\` — PayPal payment captures continue to process

## Minimising downtime

For product updates, maintenance mode is rarely needed. You can add and edit products without taking the store offline — just leave new products as **inactive** until you're ready to publish them all at once, then activate them together.

**Note:** There is no timer or scheduled enable/disable. You must manually set and unset the environment variable.`,
  },
  {
    slug: "customers/account",
    title: "Customer accounts",
    category: "Customers",
    tags: ["customers","accounts","users"],
    order: 1,
    href: "/admin/guide/customers/account",
    content: `# Customer accounts

Customers must create an account to place an order. This lets them:
- Track their orders
- Save delivery addresses
- Submit cancel/return requests

## Viewing customers

Go to **Customers** in the sidebar to see all registered accounts. The table shows:
- Name and email
- Account creation date
- Role (customer or admin)

## Customer actions

From the Customers list, you can:
- View a customer's profile
- Change their role (e.g., promote to admin)
- Delete an account

**Caution:** Deleting a customer account is permanent. Their orders will remain in the database, but the account itself (and the ability to log in) will be removed.

## Password resets

Customers can reset their own password using the "Forgot password" link on the login page. A reset email is sent to their registered email address.

If a customer says they didn't receive the reset email, check:
1. Is the email in their spam folder?
2. Is the email correct? (Typos are common — ask them to spell it out)
3. Is the SMTP server working? Ask your server administrator to check the email logs.

## Account security

Accounts are protected by email + password login. There's no social login (Google, Facebook) in this version.

Customers can change their own password from their Account → Security page.

## Admin accounts

Admin accounts have full access to the \`/admin\` panel. Only grant admin access to people you trust completely.

To create an admin account: ask your server administrator to run the admin seed script (\`npm run seed:admin\`) or promote an existing account from the Customers page.

**Admin page:** \`/admin/users\``,
  },
  {
    slug: "customers/subscribers",
    title: "Email subscribers — exporting and managing",
    category: "Customers",
    tags: ["subscribers","email","newsletter"],
    order: 2,
    href: "/admin/guide/customers/subscribers",
    content: `# Email subscribers — exporting and managing

Customers and visitors can subscribe to your newsletter using the footer signup form on the storefront. All subscribers are managed from the **Subscribers** page.

## Viewing subscribers

Go to **Subscribers** in the sidebar (under Marketing). The page shows:
- Email address
- Subscription source (footer form, account creation, etc.)
- Status: Active, Unsubscribed, or Bounced
- Date subscribed
- Date unsubscribed (if applicable)

Use the filter tabs at the top to view Active, Unsubscribed, Bounced, or All subscribers.

## Exporting subscribers

To export your subscriber list to CSV:

1. Go to **Subscribers**.
2. Choose the filter you want (e.g., "Active" for your mailing list).
3. Click **Export CSV** (top right).
4. The CSV downloads with all subscriber data for that filter.

Use this CSV to import into Mailchimp, Brevo, or any email marketing tool.

## Unsubscribing someone manually

If a customer asks to be removed from your list but didn't use the unsubscribe link:

1. Find them in the Subscribers list.
2. Click the **Unsubscribe** button in their row.
3. Their status changes to Unsubscribed.

They will no longer receive newsletter emails. Transactional emails (order confirmations, shipping updates) are not affected — those are tied to orders, not subscriptions.

## Bounced subscribers

If an email address bounces (the email can't be delivered), the subscriber is automatically marked as "Bounced". These are excluded from future sends.

You don't need to manage bounces manually — they're handled automatically.

## Important note on bulk sending

The store's email system is designed for **transactional emails only** (order confirmations, shipping updates). There is no built-in bulk newsletter sending feature. To send newsletters, export the CSV and use a dedicated tool like Mailchimp or Brevo.

**Admin page:** \`/admin/subscribers\``,
  },
  {
    slug: "customers/communication",
    title: "Email templates — subject lines and copy",
    category: "Customers",
    tags: ["email","templates","communication"],
    order: 3,
    href: "/admin/guide/customers/communication",
    content: `# Email templates — subject lines and copy

Every automated email the store sends is based on a **template** you can edit. You don't need to know code — just edit the subject and body text in plain HTML.

## Available templates

| Template | When it's sent |
|----------|---------------|
| Order confirmation | Immediately after payment is captured |
| Order shipped | When you update the order status to Shipped |
| Order delivered | When you update the order status to Delivered |
| Order refunded | After a refund is issued |
| Order cancelled | After an order is cancelled |
| Password reset | When a customer requests a password reset |
| Password changed | After a customer changes their password |
| Welcome email | When a new account is created |
| Newsletter welcome | When someone subscribes to the newsletter |
| Newsletter unsubscribed | When someone unsubscribes |
| Dispute opened (customer) | When a dispute is opened in PayPal |
| Dispute opened (admin) | Admin notification when a dispute is opened |

## How to edit a template

1. Go to **Email templates** in the sidebar (under Marketing).
2. Click **Edit** next to the template you want to change.
3. Edit the **Subject** line.
4. Edit the **Body** — it's HTML. The preview on the right updates as you type.
5. Click **Save**.

## Template variables

Use \`{{variable}}\` placeholders in your templates. The server replaces them with real data at send time. Common variables:

- \`{{name}}\` — customer's first name
- \`{{orderNumber}}\` — the order number (e.g., #1042)
- \`{{trackingNumber}}\` — courier tracking number
- \`{{storeName}}\` — your business name

**Check the template editor for the full list of available variables** — it shows which variables are valid for each template.

## Tips for good email copy

- Use the customer's name: "Hi {{name}}" feels personal
- Keep it short — one screen, no scrolling needed
- Include a link to the relevant order page
- Write subject lines that are clear: "Your 3D Ninjaz order is on its way!" beats "Order update"

**Admin page:** \`/admin/email-templates\``,
  },
  {
    slug: "products/colours",
    title: "Colour Management",
    category: "General",
    tags: [],
    order: 4,
    href: "/admin/guide/products/colours",
    content: `# Colour Management

The Colour Library is the central catalogue every product variant pulls from when you offer different colour options. It lives at \`/admin/colours\` and ships pre-seeded with ~351 colours imported from the Bambu and Polymaker reference sheets — so most of the time you are picking, not creating.

## What the Colour Library is

A single source of truth for every filament colour you stock. Each row stores a name, a hex value, a brand (Bambu / Polymaker / Other), a family (PLA, PETG, etc.), an optional sourcing code, and an optional \`previous_hex\` for tracking shade revisions. The library was seeded once from the manufacturer HTML files; from here on, you grow it manually.

## Adding a colour to a product

When you add a variant axis named **Color** (or **Colour**) on a product, the variant editor surfaces a **Pick from library** button. Click it to open the picker modal. Tick the colours you want, then **Add N colours** — variants regenerate automatically with the standard size matrix.

If a colour you want is not in the library yet, the existing **Custom (not in library)** path still works for one-off freeform values. Use it sparingly — anything you stock more than once should live in the library.

## Search and filter in the picker

Type into the search box to match across name, brand, family, and code. The **Brand** and **Family** dropdowns intersect with the search — pick "Bambu" + "PLA" + type "black" and you will see exactly Bambu PLA blacks. Colours already attached to the product show greyed out with an **Already attached** label, so you cannot add the same one twice.

## Editing a library colour

Open \`/admin/colours/[id]/edit\`. When you change a colour's name or hex, the system runs a **cascade rename** — every linked product variant updates in the same transaction. If anyone manually retyped a value on a specific product (so it diverged from the library), that manual edit is **preserved**. Cascade rename is diff-aware: it only touches variants that still match the old value.

For safety, edits that would cascade to more than 1000 variants pop a confirmation gate first.

## Archiving vs deleting

**Archive** is a soft hide — the colour disappears from the picker, but existing product variants keep working. Use this when a colour is being phased out but old products still ship.

**Delete** is hard, and is **blocked** if any product is using the colour. The block dialog lists the affected products with links and offers an **Archive instead** recovery action. You almost always want Archive.

## What customers see on the PDP

Customers see a 32px coloured swatch with the colour name caption **always visible** — no hover required. The selected swatch thickens its caption; out-of-stock swatches show a line-through. Internal sourcing codes (Bambu RFID, Polymaker SKU) are admin-only and never appear in customer HTML.

## /shop colour filter

The shop sidebar shows a **Colour** accordion listing every colour used by at least one active product. Customers can multi-select via chip clicks; the URL syncs as \`?colour=galaxy-black,jade-white\`, and the filter intersects with the existing category filter.

## Adding new colours manually

On \`/admin/colours\`, click **+ New colour**. Provide a name and hex (the native colour picker is wired in), pick the brand and family, and optionally fill in a sourcing code or \`previous_hex\`. The slug is derived automatically from the name. If a Bambu and a Polymaker colour share the same name, the slugs auto-suffix with \`-bambu\` / \`-polymaker\` so they never collide.

## Tips and gotchas

- **Codes are for sourcing only.** Bambu RFID and Polymaker SKU live on the admin row so you can restock — customers never see them.
- **Cascade rename respects manual edits.** If a product has a hand-typed value that no longer matches the library, the cascade leaves it alone. Reconcile manually if you want them back in sync.
- **The 1000-row gate is a safety net.** If you ever see it, double-check you renamed the right colour before confirming.
- **The library is seeded once.** There is no live re-import from Bambu or Polymaker by design — new colours are added manually so you stay in control of the catalogue.
- **Archive when in doubt.** Deletion is destructive and blocked anyway; Archive is reversible from the same admin page.`,
  },
  {
    slug: "index",
    title: "Welcome — how to use this guide",
    category: "Guide",
    tags: ["welcome","overview","guide"],
    order: 0,
    href: "/admin/guide/index",
    content: `# Welcome to the 3D Ninjaz Admin Guide

This guide covers every feature inside the admin panel — step by step, in plain language. You don't need to know anything about code or servers to use it.

## How to find what you need

Use the **search bar** at the top of this page to look up any topic by keyword (for example: "add product", "issue refund", "maintenance mode").

Or browse by category using the tiles below — each category groups related topics together.

## The admin panel at a glance

The sidebar on the left organises everything into groups:

- **Catalog** — Products, categories, and bulk import
- **Sales** — Orders and disputes
- **Finance** — Payments and reconciliation
- **Customers** — Customer accounts
- **Marketing** — Email templates, subscribers, coupons, reviews
- **Operations** — Shipping rates, Delyva courier, site settings

At the top of the sidebar you'll find the **Dashboard** — your daily summary of revenue, orders, and profit.

## Starting from scratch?

If you're setting up the store for the first time, go to the **[Launch Checklist](/admin/guide/launch)** first. It walks you through every setup step in the right order, from entering your business name to taking your first real payment.

## A note on saving changes

Every form in the admin panel has a **Save** button. Changes only take effect after you click Save — leaving a page without saving will discard your edits.

---

**Tip:** You can always get back to this guide by clicking **Guide** in the sidebar, under the Operations section.`,
  },
  {
    slug: "launch",
    title: "Launch Checklist — your first sale, step by step",
    category: "Guide",
    tags: ["launch","setup","checklist","first-sale"],
    order: 1,
    href: "/admin/guide/launch",
    content: `# Launch Checklist

Follow these steps in order. Each step shows what to do and how to check it worked. Tick them off as you go — your progress saves in the browser.

---

## Step 1 — Set your store identity (5 minutes)

1. Go to **Settings** in the sidebar (under Operations).
2. Enter your **Business name** (e.g., "3D Ninjaz").
3. Enter your **Contact email** — this is where customer queries go.
4. Enter your **WhatsApp number** (digits only, no spaces or + sign — e.g., \`60167203048\`). Also fill in the display version (e.g., \`+60 16 720 3048\`).
5. Fill in your social URLs for Instagram, TikTok, Facebook, and WhatsApp. Leave any blank to hide that icon from the storefront footer.
6. Click **Save settings**.

**Check it worked:** Open the storefront in a new tab. Scroll to the footer — your social icons should appear. If a URL was left blank, that icon won't show.

---

## Step 2 — Set your cost defaults (5 minutes)

1. Still on **Settings**, scroll down to the **Cost Defaults** section.
2. Enter your **Filament cost per kg** in MYR (check your supplier receipt — PLA is typically MYR 60–100/kg).
3. Enter your **Electricity cost per kWh** (TNB residential: MYR 0.29–0.57/kWh depending on your tier).
4. Enter your **Printer power draw** in kWh per hour (leave 0.150 if unsure — that's a typical 150W printer).
5. Enter your **Labor rate per hour** in MYR (covers packing, post-processing, and quality checks).
6. Leave **Overhead %** at 0 for now — you can add this later once you know your packaging costs.
7. Click **Save settings**.

**Why this matters:** These defaults are used to auto-calculate your profit margin on each product variant. You can always override them per variant later.

---

## Step 3 — Set up shipping rates (10 minutes)

There are two shipping options. Set up at least the flat-rate option first.

### Flat rates (simple)

1. Go to **Shipping (flat-rate)** in the sidebar.
2. Set a rate for each Malaysian state you ship to. Enter \`0\` for states you don't serve.
3. Set a **free-shipping threshold** — we recommend MYR 200. Orders above this get free shipping automatically.
4. Click **Save**.

### Delyva live courier (optional but recommended)

1. Go to **Delyva courier** in the sidebar.
2. Enter your **origin address** (your workshop or home address — this must be accurate for quotes to work).
3. Enter your **Delyva API token** and **Company ID** (from your Delyva dashboard at delyva.com).
4. Click **Save**, then click **Test Connection** — you should see a green "Connected" status.

**Check it worked:** Open the storefront, add a product to your bag, go to checkout, and enter a Malaysian postcode. Shipping rates should appear.

---

## Step 4 — Create your first category (3 minutes)

1. Go to **Categories** in the sidebar.
2. Type a category name (e.g., "Home Decor") and click **Add category**.
3. Optional: add a subcategory inside it (e.g., "Vases", "Planters").

**Why categories matter:** Customers can filter the shop by category. Without categories, all products appear in one big list.

---

## Step 5 — Add your first product (15 minutes per product)

1. Go to **Products** in the sidebar.
2. Click **+ New product** (top right).
3. Fill in the **Name** and **Description**.
4. Choose a **Category** and subcategory.
5. Go to the **Sizes & Pricing** tab:
   - Enable the sizes you make (Small, Medium, Large).
   - Enter a **selling price** for each enabled size.
6. Optional — go to the **Cost** tab to enter filament grams, print time, and labor minutes per size. This enables the profit tracker.
7. Upload **3 to 5 photos** using the photo uploader. The first photo is the thumbnail shown on listing cards.
8. Set the product to **Active** so it appears on the storefront.
9. Click **Save product**.

**Check it worked:** Open the storefront \`/shop\` page. Your product should appear. Click it — the size selector and prices should be correct.

**Common issue:** If the product doesn't appear, check that **Active** is toggled on and that at least one size is enabled with a price.

---

## Step 6 — Test the full purchase flow (10 minutes)

Before going live, complete a real test purchase yourself:

1. Open the storefront in a private/incognito window.
2. Create a customer account (use a personal email, not your admin email).
3. Add a product to the bag.
4. Go to checkout — enter a real Malaysian postcode. Shipping rates should appear.
5. Proceed to PayPal checkout and complete payment (you can refund yourself afterward from \`/admin/payments\`).

**Check it worked:**
- The order appears in **Orders** with status "Paid".
- You receive a confirmation email.
- The customer (you) receives a confirmation email.

**If payment fails:** Check that \`PAYPAL_ENV=live\` is set in your server environment. If it says \`sandbox\`, payments go to the test system, not real PayPal.

---

## Step 7 — Book the first shipment (2 minutes per order)

When you receive a paid order:

1. Open the order from **Orders**.
2. Scroll to the **Shipping** section.
3. Click **Book courier** — you'll see a list of couriers with live prices from Delyva.
4. Choose your preferred courier and confirm.
5. The label PDF will open automatically — print it and attach it to your parcel.
6. The order status updates to "Shipped" and the customer receives a tracking number.

---

## Step 8 — Turn off sandbox mode (1 minute)

If you set up using PayPal Sandbox (test mode), you must switch to live before real customers can pay:

1. On your server, set the environment variable \`PAYPAL_ENV=live\`.
2. Restart the Node.js app.
3. Test with a real card (then refund yourself from \`/admin/payments\`).

**Note:** Only your server administrator can change environment variables.

---

## Step 9 — Tell the world (ongoing)

- Share your store URL on Instagram, TikTok, and WhatsApp.
- Add your store URL to your bio links.
- Check **Subscribers** in the sidebar — any email signups from the footer form will appear here.

---

## Common pitfalls

**Product shows as "out of stock"**
You have inventory tracking turned ON for that variant and stock = 0. Either add stock in the product's Inventory tab, or turn tracking OFF (most 3D printing shops work on-demand, so tracking is optional).

**Shipping quote shows nothing at checkout**
Your origin postcode in Delyva settings is still a placeholder. Set your real workshop address — Delyva uses the postcode to calculate distances.

**PayPal button doesn't appear at checkout**
Your PayPal Client ID is either missing or set to sandbox credentials. Check Settings → Payments (environment variables set on the server).

**Confirmation email doesn't arrive**
Check the spam folder first. If it's not there, ask your server administrator to verify the SMTP credentials in the server environment.

**Banner announcement doesn't appear**
Go to Settings, enter text in the Banner field, and check the "Show banner" checkbox. Don't forget to Save.`,
  },
  {
    slug: "guide/whats-new-april-2026",
    title: "What's new — April 2026",
    category: "Guide",
    tags: ["changelog","new","updates","april-2026"],
    order: 2,
    href: "/admin/guide/guide/whats-new-april-2026",
    content: `# What's new — April 2026

A summary of everything added or improved in April 2026. No action is required unless noted.

---

## Products & Variants — complete redesign

The old fixed Small / Medium / Large size fields have been replaced by a fully flexible **options and variants** system.

**What this means for you:**
- Each product can now have up to 6 option types: Size, Color, Part, Material, Finish, Style
- Each option has its own ordered list of values (e.g. S / M / L, Red / Blue, Head / Arm)
- Click **Generate Variant Matrix** to auto-create all combinations
- Every variant has its own price, sale price (with schedule), stock, SKU, image, and shipping weight
- Existing products were migrated — your old sizes are now variants

**New variant features:**
- **Sale price scheduling** — set a start and end date for a discount; it activates and expires automatically
- **Pre-order toggle** — keeps an out-of-stock variant purchasable with a "Pre-order" badge on the product page
- **Per-variant weight** — overrides the product-level weight for Delyva courier quotes
- **Hover preview** — hovering a variant pill on the product page previews that variant's image
- **Single default variant** — one variant per product is marked as default and shown pre-selected

Manage variants at: \`/admin/products/<id>/variants\`

See: [Options, values, and variants](/admin/guide/products/variants-sizes)

---

## Shipping — courier whitelist and PARCEL fix

- **Courier whitelist** — only 12 approved couriers (Ninja Van, J&T, SPX, City-Link, Pos Laju, SF International, and variants) appear at checkout. Unknown couriers are filtered out automatically.
- **PARCEL type enforced** — previous "PACKAGE" type routed to Grab-only and returned zero standard couriers. The store now always uses PARCEL; any legacy PACKAGE setting is corrected automatically.
- **30 kg cap** — orders exceeding 30 kg show a clear error at checkout rather than a silent failure.
- **Duplicate webhook handling** — Delyva occasionally resends status webhooks; duplicates are silently ignored.

See: [How shipping works — Delyva auto-rates](/admin/guide/shipping/delyva-overview)

---

## Checkout — address validation improvements

Customers must now fill in all required address fields (name, phone, street, city, state, 5-digit postcode) before the courier list loads. Each missing field is highlighted individually. The **Pay Now** button is disabled with a clear reason message until both address and courier are selected.

This reduces failed orders caused by incomplete addresses.

---

## Email subscribers

- Footer newsletter signup form live on the storefront
- Public unsubscribe link in every newsletter email (\`/unsubscribed\` confirmation page)
- Admin subscriber list with filter tabs (Active / Unsubscribed / Bounced / All)
- CSV export from any filter view
- Manual unsubscribe override from the admin panel

Manage at: \`/admin/subscribers\`

See: [Email subscribers — exporting and managing](/admin/guide/customers/subscribers)

---

## Brand colours updated

The store's colour palette was updated for consistency across all pages:

| Colour | Hex |
|--------|-----|
| Blue | \`#1E8BFF\` |
| Green | \`#39E600\` |
| Purple | \`#A855F7\` |
| Ink (dark) | \`#0B1020\` |
| Cream (background) | \`#F7FAF4\` |

These colours are applied automatically — no action needed.

---

## Security

- All admin actions are protected by a server-side \`requireAdmin()\` check as the very first step. This means even if someone bypasses the login page, they cannot perform admin actions.
- Cross-origin form submissions are blocked unless the origin is on the approved list. If you ever move the store to a new domain, let your developer know so the domain is added before switching over.
- To rotate the admin password: ask your developer to run the password reset script (\`ADMIN_RESET_PASSWORD=1 npx tsx scripts/seed-admin.ts\`).

See: [Security and access](/admin/guide/operations/security)`,
  },
  {
    slug: "operations/email-templates",
    title: "Customising automated emails",
    category: "Operations",
    tags: ["email","templates","automated"],
    order: 1,
    href: "/admin/guide/operations/email-templates",
    content: `# Customising automated emails

The store sends transactional emails automatically for key events: order confirmation, shipping updates, refunds, password resets, and more.

All templates are editable from the admin panel.

## Getting to the templates

1. Go to **Email templates** in the sidebar (under Marketing).
2. You'll see a table with all 12 templates, their current subject line, and when they were last updated.
3. Click **Edit** on any template to open the editor.

## The editor

The template editor has three parts:
1. **Subject** — the email subject line. Supports \`{{variables}}\`.
2. **Body** — the full HTML email. Supports \`{{variables}}\`. The preview panel on the right shows how it looks.
3. **Save** button — always click Save before leaving.

## Previewing before sending

The preview panel shows the rendered email with placeholder values for variables. Check:
- Does it look right on mobile? (Most people read email on their phone)
- Is the subject line short enough to display fully? (40–60 characters recommended)
- Are all \`{{variable}}\` placeholders resolving correctly?

## Making safe edits

You can safely edit:
- The subject line
- The greeting ("Hi {{name}},")
- The main body text
- The closing and sign-off
- Brand colours (if you know basic HTML)

Be careful when editing:
- Links — make sure \`href\` values point to the right pages
- Variables — don't remove \`{{\` \`}}\` from variable names or they won't substitute

## Resetting to defaults

If you make changes and something breaks, you can reset a template to its default. Ask your developer to delete the template from the database (the table is \`email_templates\`). On the next page load, the admin panel will re-seed the default.

**Admin page:** \`/admin/email-templates\``,
  },
  {
    slug: "operations/settings",
    title: "Store settings — where to configure everything",
    category: "Operations",
    tags: ["settings","configuration","store"],
    order: 2,
    href: "/admin/guide/operations/settings",
    content: `# Store settings — where to configure everything

The Settings page (\`/admin/settings\`) is the central place to configure your store's identity, contact information, tax, shipping threshold, and cost defaults.

## Sections on the Settings page

### Business info

- **Business name** — shown in emails, footer, and page titles
- This is required and cannot be left blank

### Social & Contact

- **Contact email** — where customer queries go (shown on the Contact page)
- **Contact phone** — optional phone number shown as a \`tel:\` link
- **WhatsApp number** — digits only (e.g., \`60167203048\`), used to build \`wa.me/\` links
- **WhatsApp display** — the formatted version shown to customers (e.g., \`+60 16 720 3048\`)
- **Social platform URLs** — one field per platform; leave blank to hide that platform's icon

### Announcement banner

- **Banner text** — a short message shown at the top of every storefront page (e.g., "Free shipping over MYR 200!")
- **Show banner** checkbox — enable/disable the banner without deleting the text

### Free-shipping threshold

- Orders above this MYR amount get free shipping
- Leave blank to disable free shipping

### SST settings

- **Apply SST** toggle — off by default
- **SST rate (%)** — set when you register for SST (Malaysia's Sales and Services Tax)
- Only enable this if your accountant says you need to collect SST

### Cost defaults

Used as fallback rates for the profit calculator on all products:
- Filament cost per kg (MYR)
- Electricity cost per kWh (MYR)
- Printer power draw (kWh/hr)
- Labor rate per hour (MYR)
- Overhead % (covers packaging, consumables, etc.)

Individual product variants can override these per-size.

## Saving changes

Click **Save settings** at the bottom. Changes propagate to the storefront within approximately 60 seconds (the settings are cached).

**Admin page:** \`/admin/settings\``,
  },
  {
    slug: "operations/profit",
    title: "Seeing this month's profit",
    category: "Operations",
    tags: ["profit","analytics","dashboard"],
    order: 3,
    href: "/admin/guide/operations/profit",
    content: `# Seeing this month's profit

The **Dashboard** shows your profit for the current calendar month in the "Profit this month" card.

## What the card shows

- **Profit (MYR)** — revenue minus cost for the current month
- **Margin %** — profit as a percentage of revenue
- **Revenue** — total payments captured this month
- **Total cost** — sum of all order costs (from product cost breakdowns)
- **Order count** — number of paid orders this month
- A **warning** if any orders are missing cost data (shown as a yellow alert)

## How the profit is calculated

For each order this month:

\`\`\`
Order profit = order revenue - order cost
Order cost = sum of (unit_cost × quantity) for each line item
           + any extra_cost per line item
\`\`\`

\`unit_cost\` is the cost price recorded when the order was placed (snapshotted from the variant's cost data at that time). This means even if you later change the product's cost data, historical orders keep their original cost snapshot.

## If the profit looks too high

The most common reason is **missing cost data**. If a variant had no cost data filled in when the order was placed, its \`unit_cost\` is zero — making it look like pure profit.

The warning message tells you how many orders have missing cost data this month. Open those orders and check whether the product's cost breakdown was set.

## Revenue chart and top products

Below the profit card, the Dashboard also shows:
- **Revenue chart** — daily revenue for the selected range (7d / 30d / 90d)
- **Top products** — which products are selling the most
- **Funnel** — a conversion funnel showing visitors → product views → orders

Use the range tabs (7d / 30d / 90d) to change the time window for the chart and funnel. The "Profit this month" card always shows the current calendar month regardless of the range tab.

**Admin page:** \`/admin\``,
  },
  {
    slug: "operations/backup-restore",
    title: "What's backed up and where",
    category: "Operations",
    tags: ["backup","restore","database"],
    order: 4,
    href: "/admin/guide/operations/backup-restore",
    content: `# What's backed up and where

## What the store stores

Your store has two types of data to protect:

### Database (MariaDB)

This contains everything important:
- All orders and order history
- All customer accounts
- All products, variants, categories
- Payment records
- Email subscribers
- Settings and templates

**Where it lives:** cPanel MariaDB on your hosting server (\`3dninjaz.com\`).

**How to back up:**
1. Log into cPanel (\`https://3dninjaz.com:2083\`).
2. Go to **phpMyAdmin** or **Backup**.
3. Export the full database as a \`.sql\` file.
4. Save it to your computer and to a cloud drive (Google Drive or Dropbox).

**How often:** Monthly at minimum. Weekly is safer if you're actively adding products and taking orders.

### Product images

Product photos are stored on the server at \`public/uploads/products/\`.

**Where it lives:** The server's filesystem.

**How to back up:**
1. Connect via FTP (FileZilla or similar) using your cPanel FTP credentials.
2. Download the \`public/uploads/\` folder to your computer.
3. Save to an external drive or cloud storage.

## What is NOT backed up automatically

There is no automatic backup system configured out of the box. You must do this manually, or ask your server administrator to set up an automated backup cron job.

## Restoring from backup

If something goes wrong (accidental deletion, server crash):
- For database: import the \`.sql\` file via phpMyAdmin → Import.
- For images: re-upload the folder via FTP.

Contact your server administrator for help with restoration — it's a technical process.

## Recommendation

Create a shared folder in Google Drive or Dropbox for store backups. Once a month, export the database and upload the new export to that folder. Label the files by date (e.g., \`db-backup-2026-04-01.sql\`).

This takes 5 minutes and protects months of work.`,
  },
  {
    slug: "operations/security",
    title: "Security and access",
    category: "Operations",
    tags: ["security","admin","password","access"],
    order: 5,
    href: "/admin/guide/operations/security",
    content: `# Security and access

## Admin login

The admin panel is at \`/admin\`. Only accounts with the **admin** role can access it. If you try to open any admin page while logged out, you'll be redirected to the login page.

There is one admin account. Do not share the password.

## Rotating the admin password

If you need to change the admin password (recommended after any security concern):

1. Contact your developer.
2. Ask them to run the admin password reset script.
3. You'll receive the new password via a secure channel.

The reset does not affect any customer sessions or orders.

## What "admin protected" means

Every admin action — saving a product, approving an order, exporting subscribers — is verified on the server before anything happens. This means that even if someone somehow loads an admin page, they cannot make changes without a valid admin session. This protection is separate from the login page redirect and acts as a second line of defence.

## Approved origins (cross-origin security)

The store only accepts admin form submissions from its own domain (\`app.3dninjaz.com\`). If the store is ever moved to a new domain, the developer must update the approved origins list before switching. Failing to do this will cause all admin forms to silently reject submissions after the domain change.

## Sessions

Admin sessions are stored securely server-side. Sessions expire after a period of inactivity. If you're unexpectedly logged out, just log back in — this is normal behaviour.

## What to do if the admin account is compromised

1. Contact your developer immediately.
2. They will rotate the password and invalidate all active sessions.
3. Review recent orders and product changes for anything unexpected.

**Admin page:** \`/admin/settings\``,
  },
  {
    slug: "orders/overview",
    title: "Orders — the life cycle",
    category: "Orders",
    tags: ["orders","status","lifecycle"],
    order: 1,
    href: "/admin/guide/orders/overview",
    content: `# Orders — the life cycle

Every purchase creates an order. Orders move through a series of statuses as you process, pack, and ship them.

## Order statuses

| Status | Meaning |
|--------|---------|
| **Pending** | Order created but payment not yet captured (rare for web orders; common for manual orders awaiting payment) |
| **Paid** | PayPal payment captured. Ready to print and pack. |
| **Processing** | You've started working on the order (optional intermediate step) |
| **Shipped** | Courier booked and parcel handed over. Tracking number assigned. |
| **Delivered** | Parcel delivered to customer |
| **Cancelled** | Order cancelled (see below) |
| **Refunded** | Full or partial refund issued |

## How to change an order's status

1. Open the order from **Orders** in the sidebar.
2. In the **Update status** section, choose the new status from the dropdown.
3. Optionally add an internal note (visible to admin only, not the customer).
4. Click **Update**.

## Order timeline

Every status change is recorded in the **Timeline** section of the order page. This gives you a full history of when the order moved through each stage, along with any notes.

## Finding a specific order

The Orders page lists all orders, newest first. Use the **status filter** tabs at the top to narrow down to Paid, Shipped, etc.

## What's on the order page

- Customer name and email
- Delivery address
- Line items (products, sizes, quantities, prices)
- Payment status and PayPal capture ID (for paid orders)
- Shipping panel (courier booking and tracking)
- Cost and profit panel (if cost data was entered on the product)
- Refund history (if any refunds were issued)
- Status change form
- Internal notes
- Requests (cancel/return requests from the customer)

**Admin page:** \`/admin/orders\``,
  },
  {
    slug: "orders/manual-orders",
    title: "Adding orders that bypass checkout",
    category: "Orders",
    tags: ["manual orders","payment link","whatsapp"],
    order: 2,
    href: "/admin/guide/orders/manual-orders",
    content: `# Adding orders that bypass checkout

Manual orders let you create an order on behalf of a customer who contacted you via WhatsApp or email, without them going through the online checkout.

This is useful when:
- A customer orders via WhatsApp and wants to pay online
- You're quoting for a custom 3D print job
- A customer can't complete checkout themselves

## How to create a manual order

1. Go to **Orders** in the sidebar.
2. Click **+ New manual order** (top right).
3. Fill in the form:
   - **Customer email** — the customer's email address (they don't need an account, but an account must exist if they're a registered user)
   - **Delivery address** — name, address lines, city, state, postcode
   - **Line items** — add each product and size manually with a price
   - **Shipping amount** — enter a flat shipping amount for this order
   - **Notes** — internal notes (e.g., "WhatsApp order from +60xx")
4. Click **Create order**.

The order is created with status **Pending**.

## Collecting payment

After creating the order:

1. Open the order from **Orders**.
2. In the **Payment** section, click **Generate payment link**.
3. Copy the payment link and send it to the customer via WhatsApp or email.
4. The customer opens the link, clicks PayPal, and pays.
5. The order status automatically updates to **Paid** when payment is captured.

## Payment link expiry

Payment links expire after 24 hours. If the customer hasn't paid by then, generate a new link from the same order page.

## Manual orders vs web orders

Manual orders are identical to web orders once paid — they have the same shipping, tracking, and refund features. The only difference is how they were created and how payment was collected.

**Admin page:** \`/admin/orders/new\``,
  },
  {
    slug: "orders/refunds",
    title: "How to issue a refund",
    category: "Orders",
    tags: ["refunds","payments","paypal"],
    order: 3,
    href: "/admin/guide/orders/refunds",
    content: `# How to issue a refund

Refunds are processed through PayPal. The money goes back to the customer's original payment method.

## When to issue a refund

- Customer received a damaged or incorrect product
- You can't fulfil the order (out of filament, printer broke)
- Customer requested a return and you've agreed
- Order was cancelled after payment

## How to issue a refund

1. Go to **Payments** in the sidebar.
2. Find the order using the date filter or by looking in **Orders** and opening the order.
3. In the Payments list, click the order number.
4. On the payment detail page, click **Issue refund**.
5. Enter the refund amount (you can do a partial refund by entering less than the full total).
6. Add a reason (optional — for your records).
7. Click **Confirm refund**.

PayPal processes the refund immediately. It takes **1–5 business days** for the money to appear in the customer's account, depending on their bank.

## Partial refunds

You can issue multiple partial refunds on the same order, up to the total captured amount. For example, if an order was MYR 95 and you want to refund shipping only (MYR 15), enter \`15.00\`.

The refund history on the payment detail page shows every refund issued, with amounts, timestamps, and reasons.

## Checking refund status

After issuing a refund, the payment detail page shows the refund in the history. The order in the **Payments** list shows a yellow "partial" or red "full" badge in the Refunded column.

## Limits

- You cannot refund more than the total captured amount
- Once fully refunded, the Refund button is disabled
- Refunds must be issued within 180 days of the original payment (PayPal policy)

**Admin page:** \`/admin/payments/[orderId]/refund\``,
  },
  {
    slug: "orders/disputes",
    title: "Disputes — when customers escalate",
    category: "Orders",
    tags: ["disputes","paypal","escalation"],
    order: 4,
    href: "/admin/guide/orders/disputes",
    content: `# Disputes — when customers escalate

A dispute is opened when a customer raises a problem directly with PayPal — for example, they claim they didn't receive the parcel, or the item was significantly different from the description.

Disputes are serious. If you don't respond, PayPal may automatically rule in the customer's favour and refund them.

## Where to see disputes

Go to **Disputes** in the sidebar. Disputes are synced from PayPal automatically (every 15 minutes). You can also click **Refresh** to force an immediate sync.

## Dispute statuses

| Status | Meaning |
|--------|---------|
| Open | Dispute is active — you need to act |
| Waiting for buyer response | You've responded; waiting for the customer |
| Waiting for seller response | PayPal is waiting for you to respond |
| Under review | PayPal is reviewing the evidence |
| Resolved | Dispute is closed |

## How to respond to a dispute

1. Open the dispute from the **Disputes** page.
2. Read the reason and the customer's message.
3. Choose an action:
   - **Accept claim** — agree to refund the customer (PayPal processes it automatically)
   - **Escalate to PayPal** — ask PayPal to mediate (use this if you believe the customer's claim is wrong)
   - **Provide evidence** — upload tracking info, photos, or a description to support your case

## Providing evidence

Good evidence includes:
- Courier tracking screenshot showing "Delivered"
- A photo of the packaged item before shipping
- Any WhatsApp/email messages where the customer confirmed the product was as described

Upload files using the evidence uploader in the dispute detail. Accepted formats: PDF, JPG, PNG.

## Response time

PayPal typically gives sellers **10 days** to respond to a dispute before it's automatically decided in the buyer's favour. Respond as quickly as possible.

## Tips for avoiding disputes

- Always book with a tracked courier (so you have proof of delivery)
- Photograph products before shipping
- Respond promptly to customer WhatsApp/email queries — customers who feel ignored escalate to PayPal

**Admin page:** \`/admin/disputes\``,
  },
  {
    slug: "orders/cancellation",
    title: "Cancelling an order (manual process)",
    category: "Orders",
    tags: ["cancel","orders"],
    order: 5,
    href: "/admin/guide/orders/cancellation",
    content: `# Cancelling an order (manual process)

Order cancellation is currently a manual process. There's no automated "cancel" flow — you update the status yourself and handle the refund separately if the customer has already paid.

## How to cancel an unpaid order

1. Open the order from **Orders**.
2. In the **Update status** section, change the status to **Cancelled**.
3. Add an internal note explaining why (e.g., "Customer requested cancellation by WhatsApp").
4. Click **Update**.

No refund is needed for unpaid orders.

## How to cancel a paid order

1. First, issue a refund. Go to **Payments**, open the order, and issue a full refund. See the [Refunds guide](/admin/guide/orders/refunds).
2. Once the refund is processed, go back to **Orders** and update the status to **Cancelled**.
3. Add a note (e.g., "Cancelled on customer request — full refund issued via PayPal").

**Important:** Always process the refund before marking as cancelled. Marking as cancelled without a refund does not automatically return the money to the customer.

## Customer cancel/return requests

Customers can submit a cancel or return request from their account page. These requests appear on the **order detail page** in the admin panel, under the "Requests" section.

You can **approve** or **reject** each request:
- Approving a cancel request = you agree to cancel. You still need to manually update the status and issue a refund if paid.
- Approving a return request = you agree to accept the return. Arrange the return shipping with the customer via WhatsApp.

**Note:** Automated cancellation emails are on the roadmap but not yet sent automatically. If you cancel an order, notify the customer via WhatsApp or email manually.`,
  },
  {
    slug: "payments/overview",
    title: "How PayPal works — live and sandbox",
    category: "Payments",
    tags: ["paypal","payments","sandbox","live"],
    order: 1,
    href: "/admin/guide/payments/overview",
    content: `# How PayPal works — live and sandbox

All payments on 3D Ninjaz go through **PayPal**. Customers can pay with a PayPal account or any debit/credit card via PayPal's guest checkout.

## Live vs sandbox mode

The store operates in one of two modes:

| Mode | What it means |
|------|--------------|
| **Sandbox** | Test mode — no real money moves. Use PayPal test accounts to simulate purchases. |
| **Live** | Real mode — customers pay real money into your PayPal business account. |

The mode is set by the \`PAYPAL_ENV\` environment variable on the server. **Before going live, confirm this is set to \`live\` with your server administrator.**

## Where payments go

When a customer pays, the money goes directly into your **PayPal Business account**. It's available for withdrawal to your Malaysian bank account according to PayPal's normal processing time (typically 1–3 business days).

## Viewing captured payments

Go to **Payments** in the sidebar to see all captured PayPal transactions. Each row shows:
- Order number
- Customer name and email
- Gross amount (what the customer paid)
- PayPal fee (their processing fee — approximately 3–4% + MYR 2)
- Net amount (what lands in your PayPal account)
- Refunded amount (if any)
- Date and Capture ID

## PayPal fee

PayPal deducts a fee from each transaction. As of 2025, Malaysian merchants pay roughly **3.4% + MYR 2** per transaction. This is shown in the Payments table so you can see your true net earnings.

## Finding a specific payment

Use the date range filter (From / To) on the Payments page to narrow down transactions. You can also filter by refund status (no refunds / partial / full).

**Admin page:** \`/admin/payments\``,
  },
  {
    slug: "payments/reconciliation",
    title: "Nightly reconciliation",
    category: "Payments",
    tags: ["reconciliation","paypal","drift"],
    order: 2,
    href: "/admin/guide/payments/reconciliation",
    content: `# Nightly reconciliation

Every night at 3:00 AM (Malaysian time), the store automatically compares its local order records against PayPal's transaction report. This process is called **reconciliation**.

## What reconciliation checks

It compares:
- Which orders the store recorded as paid
- Which transactions PayPal actually processed

If the numbers don't match — for example, a payment was captured in PayPal but the order status wasn't updated, or vice versa — this is called **drift**.

## Where to see reconciliation results

Go to **Reconciliation** in the sidebar (under Finance). The page shows a list of nightly runs, each with:
- Run date
- Status: \`ok\` (no drift), \`drift\` (mismatch found), or \`error\` (run failed)
- Number of PayPal transactions
- Number of local transactions
- Drift count

Click any run date to see the full detail — which specific orders drifted and by how much.

## What to do if there's drift

A drift count > 0 means the store's records don't fully match PayPal's. Common causes:
- A payment captured in PayPal but the order webhook failed to update
- A refund issued directly from PayPal Business (not through the admin panel)
- A chargeback initiated by a customer

**What to do:**
1. Open the drift detail from the Reconciliation page.
2. Match each drifted transaction to its order in the **Orders** page.
3. Manually update the order status if needed.
4. If you see an unexpected charge or refund in PayPal that you don't recognise, contact PayPal.

## Sidebar badge

If the latest reconciliation run found drift, a red badge appears on the Reconciliation link in the sidebar. It clears once you've reviewed the run.

## Manual run

The cron runs automatically. If you need to run it manually (for example, after updating server settings), ask your server administrator to run: \`node scripts/cron/reconcile-paypal.cjs\`

**Admin page:** \`/admin/recon\``,
  },
  {
    slug: "products/overview",
    title: "Products, variants, and how they work",
    category: "Products",
    tags: ["products","variants","overview"],
    order: 1,
    href: "/admin/guide/products/overview",
    content: `# Products, variants, and how they work

Every item in your store is a **product**. Each product can have up to 6 **options** (e.g., Size, Color, Part), each with its own set of **values**. The system auto-generates a **variant** for every combination of values — each with its own price, stock, SKU, image, and shipping weight.

## The structure

\`\`\`
Product
 ├── Basic info: name, description, category, photos, shipping weight
 └── Options (e.g. Size, Color)
      ├── Option values (e.g. Small, Medium, Large)
      └── Variants — auto-generated for each combination
           ├── Small / Red — price, sale price, cost, stock, SKU, image, weight
           ├── Small / Blue — ...
           └── Medium / Red — ...
\`\`\`

Each variant is independent. You can set different prices, stock levels, images, and shipping weights per variant.

## Key product fields

**Name and description** — What customers see on the product page and in search results. Write clearly and describe the material (e.g., "PLA plastic"), dimensions, and what makes it unique.

**Category / Subcategory** — Groups products in the shop filter. You must create categories first (see the [Categories guide](/admin/guide/products/categories)).

**Active toggle** — Only active products appear in the storefront. Inactive products are hidden from customers but remain in the database. Use this to take a product offline temporarily without deleting it.

**Featured toggle** — Featured products appear in the "Featured" section on the homepage. Pick your best sellers.

**Material type** — Optional. Shown on the product page (e.g., "PLA", "PETG", "Resin").

**Estimated production days** — How many working days it takes to print and dispatch. Shown to customers at checkout.

**Shipping weight (kg)** — Default weight used when calculating Delyva courier quotes. Individual variants can override this with their own weight.

## Variants in detail

Each variant has:
- **Selling price** — what the customer pays
- **Sale price + schedule** — optional discounted price with optional start/end date
- **Cost fields** (optional) — filament grams, print time, labor minutes, used to calculate your profit margin
- **SKU** — auto-generated reference code; you can override it
- **Image** — optional per-variant photo shown in the gallery when that variant is selected
- **Weight (g)** — overrides the product-level shipping weight for Delyva quotes
- **Track Stock / Stock count** — optional; see the [Inventory guide](/admin/guide/products/inventory)
- **In Stock toggle** — quickly mark a variant available or unavailable
- **Pre-order** — keeps an out-of-stock variant purchasable; shows "Pre-order" label on the product page
- **Default flag** — exactly one variant per product is the default shown when the page loads

For full instructions on setting up options and generating variants, see [Options, values, and variants](/admin/guide/products/variants-sizes).

## Photos

You can upload multiple photos per product. The first photo (index 0) is the thumbnail shown on listing cards. You can drag to reorder them, or choose a different thumbnail.

**Tip:** Aim for square photos (1:1 ratio) with a clean white or neutral background. They display best on product cards and reduce load time.

## Where to manage products

Go to **Products** in the sidebar to see all products. Click any product name to edit it. Use **+ New product** to add a new one. From the product edit page, click **Manage Variants** to set up options, values, and per-variant pricing.`,
  },
  {
    slug: "products/add-product",
    title: "How to add a new product",
    category: "Products",
    tags: ["products","add","new"],
    order: 2,
    href: "/admin/guide/products/add-product",
    content: `# How to add a new product

1. Go to **Products** in the sidebar.
2. Click **+ New product** (top right).
3. Fill in the **Name** — keep it short and descriptive (e.g., "Mini Dragon Figurine").
4. Write a **Description** — tell customers what it's made of, the size range, and any custom options.
5. Choose a **Category** (and subcategory if you have them set up).
6. Set the **Material type** if relevant (e.g., PLA, PETG, Resin).
7. Enter **Estimated production days** — how many working days from order to dispatch.
8. Enter a **Shipping weight (kg)** — used as the default weight for courier quotes. You can override per-variant later.

## Uploading photos

1. In the **Photos** section, click the upload area or drag-and-drop images.
2. Upload 3 to 5 photos per product.
3. The first photo is the thumbnail on listing cards. You can choose a different thumbnail by clicking the star icon.

## Setting active / featured

- **Active** — must be on for the product to appear in the storefront. Off by default on new products — don't forget to enable it.
- **Featured** — shows the product in the homepage "Featured" section.

## Saving the product

Click **Save product** at the bottom. You'll be taken to the product edit page.

## Adding variants (sizes, colors, etc.)

After saving the product, click **Manage Variants** to set up your options and prices.

1. Add your option types (e.g., Size, Color, Part).
2. Add values for each option (e.g., S / M / L for Size).
3. Click **Generate Variant Matrix** — the store creates a row for each combination.
4. Set the **price**, **stock**, **SKU**, and optionally an **image** and **weight** for each variant.
5. Mark one variant as the **Default** — it's shown pre-selected on the product page.
6. Save variants.

See the full [Options, values, and variants guide](/admin/guide/products/variants-sizes) for details on pre-order, sale pricing, and weight per variant.

## Adding cost data (optional but recommended)

Each variant has a **Cost** section. Fill it in to track your profit margin:

- **Filament grams** — how much filament does this variant use?
- **Print time (hours)** — total hours in the printer
- **Labor minutes** — packing, post-processing, QC time
- **Other cost** — any extra materials (supports, supports removal, etc.)

Leave any field blank to fall back to your store-wide defaults (set in Settings → Cost Defaults).

**Verify:** Open \`/shop\` in the storefront. Your product should appear if it's active. Click it to check the variant selector, prices, and photos look correct.

**Tip:** Empty cost fields are fine — they default to store-level defaults from Settings. Only override per-variant if that variant uses significantly more or less filament.`,
  },
  {
    slug: "products/photos",
    title: "Product photos — good ones convert",
    category: "Products",
    tags: ["photos","images","products"],
    order: 3,
    href: "/admin/guide/products/photos",
    content: `# Product photos — good ones convert

A great photo makes the difference between a customer clicking "Add to bag" and leaving the page. Here's what works.

## How many photos to upload

Upload **3 to 5 photos** per product:
1. Main front view — clean background, well lit
2. Side or angle view — shows depth and detail
3. Scale reference — show it next to a hand, coin, or ruler so customers know the actual size
4. Detail close-up — texture, infill pattern, finish quality
5. Context shot — the product in use or on a shelf (optional but effective)

## Photo quality tips

- **Use natural light** — near a window on an overcast day gives soft, even light with no harsh shadows
- **Clean background** — white cardboard, a plain table, or a sheet works well
- **Steady camera** — use a phone tripod or prop your elbow on a table to avoid blur
- **Square crops** — the product card on listings is square (1:1). Crops that are too tall or wide get letterboxed

## Technical requirements

- Minimum width: 800px (1200px+ recommended)
- Format: JPG or PNG (the server converts to WebP automatically)
- File size: under 10 MB per photo (the server will compress it)

## Setting the thumbnail

The **first photo** is used as the thumbnail on product listing cards. To change which photo is the thumbnail:

1. Open the product for editing.
2. In the Photos section, click the star icon on the photo you want as thumbnail.

## Reordering photos

Drag photos left or right in the uploader to reorder them. The order you set here is the order customers see them in the photo gallery on the product page.

## Deleting a photo

Click the **X** button on any photo to remove it. Changes take effect when you click **Save product**.

**Tip:** Never delete all photos from an active product — a product with no photos won't display a thumbnail in the listing and will look broken to customers.`,
  },
  {
    slug: "products/variants-sizes",
    title: "Options, values, and variants",
    category: "Products",
    tags: ["variants","options","sizes","pricing","sku","pre-order","stock"],
    order: 4,
    href: "/admin/guide/products/variants-sizes",
    content: `# Options, values, and variants

Every product can have up to **6 options** — attribute types like Size, Color, Part, Material, Finish, or Style. Each option has a list of **values** (for example, Size has values S, M, L). The store then generates a **variant** for every combination of values.

> **What changed in April 2026:** The old fixed Small/Medium/Large size fields have been replaced by this generic system. Existing products were migrated automatically.

## Understanding the structure

- **Option** = the attribute type (e.g., "Size", "Color", "Part")
- **Value** = a choice within that option (e.g., "S", "M", "L" for Size; "Red", "Blue" for Color)
- **Variant** = one specific combination (e.g., Size: M / Color: Red)

A product with two options — Size (S, M, L) and Color (Red, Blue) — will generate 6 variants: S/Red, S/Blue, M/Red, M/Blue, L/Red, L/Blue.

## Managing variants

Go to the product edit page and click **Manage Variants** (or go directly to \`/admin/products/<product-id>/variants\`).

### Step 1 — Define your options

1. Click **Add option**.
2. Choose the option type from the dropdown (Size, Color, Part, Material, Finish, Style).
3. Add values for that option — type each value and press Enter. You can drag values to reorder them.
4. Repeat for up to 6 options.

### Step 2 — Generate the variant matrix

Once your options and values are set, click **Generate Variant Matrix**. The store expands all option/value combinations into individual variant rows. Existing variants that already have sales history are kept as-is and merged in.

### Step 3 — Fill in each variant row

Each variant row has these editable fields:

| Field | What it does |
|-------|-------------|
| **Price (MYR)** | The selling price customers see |
| **Sale price** | Optional discounted price. Set a start and end date to schedule a sale |
| **Stock** | Number of units on hand (only used when Track Stock is on) |
| **Track Stock** | Toggle on to deduct stock when orders are placed |
| **In Stock** | Quick toggle to mark a variant available or unavailable (overrides stock count) |
| **SKU** | Internal reference code. Auto-generated as \`3DN-{SLUG4}-{INITIALS}\` but you can override it |
| **Image** | A photo specific to this variant. Shown in the product gallery when the customer selects this variant |
| **Weight (g)** | Shipping weight in grams. Overrides the product-level weight for Delyva courier quotes |
| **Pre-order** | See below |
| **Default** | The variant shown first when a customer opens the product page |

### Setting a default variant

Exactly one variant per product is the default. Mark it with the **Default** toggle. Marking a new variant as default automatically unmarks the previous one. The default variant is shown pre-selected on the product page.

### Pre-order

Turn on **Pre-order** for a variant to keep it purchasable even when it is out of stock (tracked stock = 0 or "In Stock" is off). The variant shows a "Pre-order" label on the product page instead of "Out of stock", and customers can still add it to their bag.

Use this for popular variants that you know you will restock soon.

### How out-of-stock works

A variant is hidden from the storefront selector when:
- **In Stock** is toggled off, **and** Pre-order is off
- **or** Track Stock is on, stock has reached 0, **and** Pre-order is off

If Pre-order is on, the variant stays available regardless of stock.

### Variant image hover preview

On the product page, hovering over a variant pill or swatch shows a preview of that variant's image (if one was uploaded). This helps customers see color or style differences before clicking.

## Shipping weight per variant

The weight used for Delyva courier quotes follows this priority:

1. Variant's own **Weight (g)** field (if filled in)
2. Product-level **Shipping weight** (if the variant weight is blank)
3. Default fallback: 1 kg

Fill in per-variant weights when your variants differ significantly in weight (e.g., a Large figurine vs. a Small one).

## SKU format

SKUs are auto-generated when you create a variant: \`3DN-{first 4 chars of slug}-{option initials}\`. Example: a Size M / Color Red variant of the "Mini Dragon" product might get \`3DN-MINI-MR\`. You can override the SKU at any time — just type in the field.

**Admin page:** \`/admin/products/<id>/variants\``,
  },
  {
    slug: "products/cost-breakdown",
    title: "How cost is calculated (filament, electricity, labor)",
    category: "Products",
    tags: ["cost","profit","filament","electricity","labor"],
    order: 5,
    href: "/admin/guide/products/cost-breakdown",
    content: `# How cost is calculated

The cost breakdown shows you exactly how much it costs to produce each variant, and what your profit margin is at the current selling price.

## The formula

\`\`\`
Total cost = filament cost + electricity cost + labor cost + other cost
           + overhead %
\`\`\`

Each component is calculated like this:

**Filament cost**
= (filament grams ÷ 1000) × filament cost per kg

**Electricity cost**
= print time hours × printer power kWh/hr × electricity cost per kWh

**Labor cost**
= (labor minutes ÷ 60) × labor rate per hour

**Overhead**
= overhead % × (filament + electricity + labor + other)

## Where the rates come from

Rates come from two places:

1. **Store defaults** — set in Settings → Cost Defaults. These apply to all products unless overridden.
2. **Per-variant overrides** — set on each variant. Use these when a specific product uses a specialty filament with a different cost, or when a variant requires unusually high labor.

If a variant has no override, the store default is used. If the store default is also blank, that component is treated as zero cost.

## Where to see the live calculation

Open any product for editing. In the Sizes & Pricing section, expand a size. As you fill in the cost fields, the panel shows:
- Total cost (MYR)
- Gross profit (selling price minus cost)
- Margin %

This updates live as you type.

## Profit on the dashboard

The **Dashboard** shows "Profit this month" — a calendar-month summary calculated from the cost data on each order's line items. If an order has no cost data, it's treated as zero cost (which inflates profit). The dashboard shows a warning if any orders this month are missing cost data.

**Tip:** You don't have to fill in cost data right away. Products sell normally without it. But if you want to understand your business economics, filling in cost data for your top-selling products is worth the 5 minutes.`,
  },
  {
    slug: "products/inventory",
    title: "Tracking stock and pre-order",
    category: "Products",
    tags: ["inventory","stock","tracking","pre-order"],
    order: 6,
    href: "/admin/guide/products/inventory",
    content: `# Tracking stock and pre-order

Stock tracking is **off by default**. This is intentional — most 3D printing shops print to order, so there's no pre-made stock to track.

Only turn on stock tracking if you print products in advance and store them physically.

## Turning on stock tracking

1. Open a product for editing.
2. Click **Manage Variants**.
3. In the variant row, toggle **Track Stock** on.
4. Enter the current **stock quantity**.
5. Click **Save**.

Once tracking is on for a variant, customers can only add it to their bag if stock > 0. When stock reaches zero, that variant is hidden from the storefront variant selector and shows as "Out of stock".

## Updating stock

When you receive a new batch of printed items:

1. Open the product for editing.
2. Click **Manage Variants**.
3. Update the stock number for each variant.
4. Save.

There's no automated deduction history — the stock number is a simple count you manage manually.

## Turning tracking off

If you no longer want to track stock on a variant:

1. Toggle **Track Stock** off for that variant.
2. Save.

The variant becomes available regardless of any stock number, allowing customers to order freely again.

## The "In Stock" toggle

Each variant also has an **In Stock** toggle independent of stock counting. If you toggle In Stock off, the variant is hidden from the storefront selector even if track stock is off. Use this to quickly disable a specific variant without deleting it.

## When a variant is hidden from the storefront

A variant is hidden from the product page selector when **any** of these apply:
- **In Stock** is off — and Pre-order is also off
- **Track Stock** is on, stock = 0 — and Pre-order is also off

If Pre-order is on, the variant stays visible regardless of stock or the In Stock toggle.

## Pre-order

Turn on **Pre-order** for a variant to keep it available for purchase even when it is out of stock. The variant shows a **"Pre-order"** badge on the product page instead of "Out of stock". Customers can still add it to their bag and complete checkout.

Use pre-order when:
- You know a popular variant will be restocked soon
- You want to take orders before finishing a print batch
- You're gauging demand before printing

To enable pre-order on a variant:
1. Go to **Manage Variants** for the product.
2. Toggle **Pre-order** on for the relevant variant row.
3. Save.

To end pre-order (when stock is back):
1. Add the new stock quantity.
2. Toggle **Pre-order** off.
3. Save.

**Common mistake:** If a product is unexpectedly showing as out of stock, check whether Track Stock was accidentally left on with stock = 0. Either toggle Track Stock off, top up the stock count, or enable Pre-order to keep it purchasable.`,
  },
  {
    slug: "products/categories",
    title: "Categories and subcategories",
    category: "Products",
    tags: ["categories","subcategories","organisation"],
    order: 7,
    href: "/admin/guide/products/categories",
    content: `# Categories and subcategories

Categories help customers browse the shop. Instead of scrolling through every product, they can filter by category (e.g., "Home Decor", "Toys", "Cable Management").

## How categories work

The structure is two levels deep:

\`\`\`
Category: Home Decor
  └── Subcategory: Vases
  └── Subcategory: Planters
  └── Subcategory: Wall Art

Category: Toys & Games
  └── Subcategory: Figurines
  └── Subcategory: Puzzles
\`\`\`

Products are assigned to a subcategory. On the storefront, customers filter by the top-level category.

## Creating a category

1. Go to **Categories** in the sidebar.
2. In the **Add category** form, type the category name.
3. Click **Add**.

The new category appears in the tree below.

## Creating a subcategory

1. Go to **Categories** in the sidebar.
2. In the **Add subcategory** form:
   - Choose the parent category from the dropdown.
   - Type the subcategory name.
3. Click **Add**.

## Assigning a product to a category

When creating or editing a product:

1. Choose a **Category** from the dropdown.
2. Choose a **Subcategory** from the next dropdown (it shows only subcategories that belong to the chosen category).
3. Save the product.

## Deleting a category

You can delete categories and subcategories from the category tree on the Categories page. Categories with products assigned to them cannot be deleted until those products are re-assigned or deleted.

**Tip:** Start with broad category names. You can always add subcategories later. Three to five top-level categories is usually enough for a small store — more than that and the filter starts to feel overwhelming.`,
  },
  {
    slug: "shipping/delyva-overview",
    title: "How shipping works — Delyva auto-rates",
    category: "Shipping",
    tags: ["shipping","delyva","couriers","parcel","whitelist"],
    order: 1,
    href: "/admin/guide/shipping/delyva-overview",
    content: `# How shipping works — Delyva auto-rates

3D Ninjaz supports two shipping methods:

1. **Flat rates** — simple per-state prices you set manually (e.g., "Selangor: MYR 8")
2. **Delyva live rates** — real-time quotes from couriers like J&T, Ninja Van, Pos Laju, and SPX

Most store owners start with flat rates because they're simpler. Delyva is the recommended upgrade once you're shipping regularly.

## How Delyva works

When a customer reaches checkout:

1. They fill in their full shipping address (name, phone, street, city, state, postcode).
2. The store sends their postcode and the order's weight to Delyva's API.
3. Delyva returns a list of available couriers with live prices and estimated delivery times.
4. The customer picks a courier and completes payment.
5. When you're ready to ship, **book the courier from the order detail page** — Delyva confirms the booking and provides a waybill label.

## What you need

- A Delyva account at [delyva.com](https://delyva.com)
- Your **API token** and **Company ID** from the Delyva dashboard
- Your **workshop address** (used as the pickup point for couriers)

## Setting up Delyva

See the [Delyva origin address](/admin/guide/shipping/origin-address) and [Rates and markup](/admin/guide/shipping/rates) guides.

## Approved couriers

The store only shows quotes from a curated whitelist of 12 couriers. This prevents unknown or low-quality couriers from appearing at checkout.

| Courier | Status |
|---------|--------|
| Ninja Van MY | Active |
| J&T Express MY | Active |
| SPX MY | Active |
| City-Link MY | Active |
| Pos Laju MY | Active |
| SF International | Active |
| Ninja Van MY (drop-off) | Active |
| Pos Malaysia (POSMY) | Needs merchant provisioning |
| Ninja Van MY Roadside | Needs merchant provisioning |
| Ninja Van MY (international) | Needs merchant provisioning |
| Ninja Van Doorstep MY (international) | Needs merchant provisioning |
| SF International (GE) | Needs merchant provisioning |

Couriers marked "Needs merchant provisioning" will appear once your Delyva account has those services enabled. Contact Delyva support to activate them.

## Refreshing the courier catalog

After your Delyva account is updated with new services, go to **Shipping → Delyva** in the sidebar and click **Refresh courier catalog**. This fetches the latest list from Delyva and updates the whitelist matching.

**Admin page:** \`/admin/shipping/delyva\`

## Parcel type — important

All shipments are sent as **PARCEL** type. An older setting called "PACKAGE" routes orders to Grab-only fulfillment and returns zero standard couriers. The store automatically corrects any PACKAGE setting to PARCEL — no action needed on your part.

## 30 kg parcel cap

Delyva does not accept single shipments over 30 kg. If an order's total weight exceeds 30 kg, the store shows a friendly error at checkout and the customer cannot select a courier. In this case, contact the customer to arrange a manual shipping quote (WhatsApp or email) and mark the order as shipped manually from the order detail page.

## Flat rates as a fallback

If Delyva is not configured, or if Delyva returns no available couriers for a destination, the system falls back to your flat-rate table. Keep your flat rates up to date as a safety net.

## Duplicate webhook deliveries

Delyva occasionally re-sends shipping status webhooks. The store handles this automatically — duplicate updates are silently ignored, so order status won't be updated twice.`,
  },
  {
    slug: "shipping/origin-address",
    title: "Setting your workshop address",
    category: "Shipping",
    tags: ["shipping","delyva","address","origin"],
    order: 2,
    href: "/admin/guide/shipping/origin-address",
    content: `# Setting your workshop address

Delyva uses your workshop (or home) address as the **pickup point** for all courier bookings. The address must be accurate — Delyva needs the postcode to calculate distances and determine which couriers serve your area.

## How to set it

1. Go to **Delyva courier** in the sidebar (under Operations).
2. Scroll to the **Origin address** section.
3. Fill in:
   - **Address line 1** — street address
   - **Address line 2** — unit number or floor (optional)
   - **City**
   - **State** — e.g., "Selangor"
   - **Postcode** — 5-digit Malaysian postcode
   - **Country** — Malaysia
4. Click **Save**.

## Why the postcode matters

The postcode is what Delyva uses to geocode your location. If the postcode is wrong or a placeholder (like \`00000\`), Delyva will return no courier quotes and customers will see no shipping options at checkout.

## Package defaults

Also in the Delyva settings, you can set default package dimensions and weight. These are used when a specific product variant doesn't have dimensions entered. Set them to a reasonable average — you can always adjust at booking time.

- **Default weight (kg)** — typical parcel weight for your products
- **Default dimensions (cm)** — length × width × height of your typical box

**Verify:** After saving, click **Test Connection** — it should show a green "Connected" status with your Delyva account name.`,
  },
  {
    slug: "shipping/rates",
    title: "Markup and free-shipping threshold",
    category: "Shipping",
    tags: ["shipping","rates","markup","free-shipping"],
    order: 3,
    href: "/admin/guide/shipping/rates",
    content: `# Markup and free-shipping threshold

## Flat rates (per state)

The simplest way to set shipping is per-state flat rates:

1. Go to **Shipping (flat-rate)** in the sidebar.
2. Enter a price (MYR) for each state.
3. Enter \`0\` for states you don't ship to, or leave them blank.
4. Click **Save**.

These rates appear at checkout when Delyva is not configured or returns no results.

## Free-shipping threshold

Set a minimum order value above which shipping is free:

1. Go to **Settings** in the sidebar.
2. Find the **Free-shipping threshold** field.
3. Enter a MYR value (e.g., \`200.00\`).
4. Save.

When a customer's order subtotal reaches or exceeds this amount, shipping is automatically set to MYR 0.00. We recommend MYR 200 for 3D Ninjaz — it encourages larger orders.

Leave the field blank to disable free shipping.

## Delyva price markup

If you want to add a buffer on top of Delyva's live courier rates (to cover packaging materials or as a small margin):

1. Go to **Delyva courier** in the sidebar.
2. In the **Price adjustment** section:
   - **Markup percent** — e.g., \`10\` adds 10% to all Delyva quotes
   - **Flat fee (MYR)** — a fixed amount added to every Delyva quote
3. Save.

Most small stores set both to zero and charge raw courier rates. Adjust if your packaging costs are significant.

**Tip:** The free-shipping threshold applies to both flat rates and Delyva quotes. If the order total exceeds the threshold, shipping is always free regardless of which method is used.`,
  },
  {
    slug: "shipping/booking",
    title: "Booking couriers from an order",
    category: "Shipping",
    tags: ["shipping","courier","booking","delyva"],
    order: 4,
    href: "/admin/guide/shipping/booking",
    content: `# Booking couriers from an order

Once a customer has paid, you book the shipment directly from the order detail page.

## How to book

1. Go to **Orders** in the sidebar.
2. Click the order number to open it.
3. Scroll down to the **Shipping** section.
4. Click **Book courier**.
5. The system fetches live quotes from Delyva for the customer's postcode. You'll see a list of available couriers with prices and estimated delivery times.
6. Click **Book** next to your preferred courier.
7. Delyva confirms the booking. A **consignment number** and **tracking number** appear on the page.
8. The label PDF is available immediately — click **Print label** to open it.

## What happens after booking

- The order status automatically updates to "Shipped".
- The customer receives a shipping confirmation email with their tracking number.
- The tracking timeline on the customer's order page shows live status updates from Delyva.

## If no couriers appear

This means Delyva can't find services for that destination. Possible reasons:
- The customer's postcode is outside covered areas (e.g., rural Sabah/Sarawak)
- Your origin postcode in Delyva settings is a placeholder
- Delyva's API is temporarily down

In these cases, arrange the shipment manually and update the order status to "Shipped" yourself from the order detail page.

## Cancelling a booking

You can cancel a booked shipment as long as the courier hasn't picked it up. In the Shipping section of the order, click **Cancel shipment**. Note that Delyva may reject the cancellation if the courier is already en route — the error will show inline.

**Tip:** Book courier bookings early in the day. Most couriers have morning pickup windows. If you book after midday, the pickup may be the next working day.`,
  },
  {
    slug: "shipping/tracking",
    title: "Tracking — what the customer sees",
    category: "Shipping",
    tags: ["tracking","shipping","customer"],
    order: 5,
    href: "/admin/guide/shipping/tracking",
    content: `# Tracking — what the customer sees

Once you've booked a shipment, customers can track their parcel through their account.

## What the customer sees

On the customer's order page (\`/orders/[id]\`), the **tracking timeline** shows:

- The current status (e.g., "Picked up", "In transit", "Out for delivery")
- Each status update with a timestamp
- The courier name and consignment number
- A driver card when the courier is out for delivery (name, vehicle, contact — if the courier provides this)

The tracking data comes live from Delyva and updates whenever the customer refreshes the page.

## What the admin sees

On the admin order page, the same tracking timeline appears below the shipment panel. You see the same view as the customer, plus the Delyva booking details and action buttons.

## Refreshing tracking status

If you want to force a status refresh (for example, to check if a parcel has been picked up):

1. Open the order in the admin panel.
2. In the **Shipping** section, click **Refresh status**.
3. The tracking timeline updates with the latest data from Delyva.

## Tracking number format

The tracking number format varies by courier:
- **J&T**: \`JT...\` format
- **GrabExpress**: alphanumeric booking reference
- **Lalamove**: booking order number

Customers can also track their parcel directly on the courier's website using this number if they prefer.

**Note:** Tracking status can take 1–4 hours to appear after pickup, as couriers update their systems in batches. If the status shows "Pending pickup" for several hours, that's normal — it means the courier hasn't scanned the parcel yet.`,
  },
  {
    slug: "shipping/labels",
    title: "Printing shipping labels",
    category: "Shipping",
    tags: ["labels","shipping","printing"],
    order: 6,
    href: "/admin/guide/shipping/labels",
    content: `# Printing shipping labels

After booking a courier via Delyva, the shipping label is available immediately.

## How to print a label

1. Open the order from **Orders** in the sidebar.
2. Scroll to the **Shipping** section.
3. After a successful booking, a **Print label** button appears.
4. Click it — the label opens as a PDF in a new browser tab.
5. Print it from your browser (File → Print, or Ctrl+P / Cmd+P).

## Label format

Delyva generates labels in A4 or A6 format depending on the courier. Most thermal label printers use A6 (100mm × 150mm). You can also print on plain A4 paper and fold it into the label sleeve on the parcel.

## What's on the label

- Sender address (your workshop address from Delyva settings)
- Recipient address (customer's delivery address)
- Consignment number and barcode
- Courier service name

## If the label doesn't open

- Check that your browser isn't blocking pop-ups for this site
- Try a different browser (Chrome works reliably)
- If the label URL has expired, refresh the order page and click Print label again — Delyva regenerates them on demand

## Sticking the label

- Use a clear label sleeve (available at stationery shops or on Shopee) to protect the label from moisture
- Make sure the barcode is flat and not folded — the courier scanner needs a clear read
- Place the label on the largest flat surface of the parcel

**Tip:** Print labels the night before your pickup window. Some couriers' morning pickups are very early (before 9am).`,
  },
];
